name: scan_pdf
description: Aplicaci贸n para escanear documentos y generar PDFs
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # Escaneo de documentos
  cunning_document_scanner: ^1.3.0

  # Generaci贸n de PDFs
  pdf: ^3.11.1

  # Manejo de archivos
  path_provider: ^2.1.4

  # Compartir archivos
  share_plus: ^10.1.2

  # Permisos
  permission_handler: ^12.0.1

  # Internacionalizaci贸n
  intl: ^0.20.2 # UI
  cupertino_icons: ^1.0.8

  # Monetizaci贸n
  google_mobile_ads: ^5.1.0
  in_app_purchase: ^3.2.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "ScanPDF_for_students_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "ScanPDF_for_students_icon.png"
